# docker/docker-compose.yml

# Load all key=val pairs from the project‐root .env
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: camagru-php
    expose:
      - "9000"
    networks:
      - camagru
    volumes:
      - ../public:/var/www/public
      - ../src:/var/www/src
      - ../vendor:/var/www/vendor
      - ../database:/var/www/database
    depends_on:
      - db
    env_file:
      - ../.env
    restart: always

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    container_name: camagru-nginx
    ports:
      - "8080:80"
    volumes:
      - ../public:/var/www/public
      - ../src:/var/www/src
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - camagru
    restart: always

  db:
    image: mariadb:10.5
    container_name: camagru-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camagru
      MYSQL_USER: tiboitel
      MYSQL_PASSWORD: root
    expose:
      - "3306"
    networks:
      - camagru
    restart: always

networks:
  camagru:
    driver: bridge

