version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: camagru-nginx
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
      - ../docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - camagru
    restart: always

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: camagru-php
    expose: 
      - "9000"
    networks:
      - camagru
    volumes:
      - ../src:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=camagru
      - DB_USER=root
      - DB_PASS=root
    restart: always

  db:
    image: mariadb:10.5
    container_name: camagru-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camagru
      MYSQL_USER: tiboitel
      MYSQL_PASSWORD: root
    expose: 
      - "3306"
    restart: always

networks:
  camagru:

